### ISSUE TITLE
APP VERSION missing when charts loaded using pyhelm

### ISSUE THREAD

**Issue by miff2000** [ukfast/pyhelm#1]
When using Ansible to deploy a new chart into Kubernetes, using PyHelm, the resulting chart doesn't have the `APP VERSION` column populated. Deploying the chart using `helm` itself doesn't have this issue.

A correct deployment, run using this command:
```bash
helm install --name nginx-ingress --namespace nginx-ingress -f helm/nginx-ingress/values.yml stable/nginx-ingress
```
 looks like this:
```bash
$ helm list
NAME            REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE
gitlab-runner   4               Tue Apr 16 11:45:32 2019        DEPLOYED        gitlab-runner-0.3.0     11.9.0          gitlab-runners
ingress-nginx   1               Thu May  9 06:50:50 2019        DEPLOYED        nginx-ingress-1.6.0     0.24.1          ingress-nginx
staging         1               Thu May  9 15:29:27 2019        DEPLOYED        ci-cd-helm-1.0.0        1.0             peter-boulderstone-ci-cd-test-project
uat-698-125     29              Mon Apr 29 12:53:52 2019        DEPLOYED        ci-cd-helm-1.0.0        1.0             ukfast-api-ukfast-safedns
ukfast-api-kong 1               Tue Apr 30 11:21:50 2019        DEPLOYED        kong-0.9.9              1.1             ukfast-api-kong
```

The deployment done via Ansible, using this play:
```yaml
- name: Deploy NGiNX Ingress 
  helm:
    host: tiller-host
    chart:
      name: nginx-ingress
      version: 1.6.0
      source:
        type: repo
        location: https://kubernetes-charts.storage.googleapis.com
      values: "{{ lookup('file', 'helm/nginx-ingress/values.yml') }}"
    state: present
    name: ingress-nginx
    namespace: ingress-nginx
  delegate_to: "{{ groups['kube-master'][0] }}"
  tags: helm_charts
```
Yields the incorrect release, missing the `APP VERSION` of `0.24.1`
```bash
$ helm list
NAME            REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE
gitlab-runner   4               Tue Apr 16 11:45:32 2019        DEPLOYED        gitlab-runner-0.3.0     11.9.0          gitlab-runners
ingress-nginx   1               Fri May 10 16:03:29 2019        DEPLOYED        nginx-ingress-1.6.0                     ingress-nginx
staging         1               Thu May  9 15:29:27 2019        DEPLOYED        ci-cd-helm-1.0.0        1.0             peter-boulderstone-ci-cd-test-project
uat-698-125     29              Mon Apr 29 12:53:52 2019        DEPLOYED        ci-cd-helm-1.0.0        1.0             ukfast-api-ukfast-safedns
ukfast-api-kong 1               Tue Apr 30 11:21:50 2019        DEPLOYED        kong-0.9.9              1.1             ukfast-api-kong
``` 

This `APP VERSION` is read from the value `appVersion` [here](https://github.com/helm/charts/blob/40637f335b67b33578a32ae57db9c6651f2e8c20/stable/nginx-ingress/Chart.yaml#L3)
